### ISSUE TITLE
multiprocessing: string argument without an encoding

### ISSUE THREAD

**Issue by valeriob01** [SebKuzminsky/pycam#106]
Enabled 4 parallel local processes
Allow remote processing
Traceback (most recent call last):
  File "/home/sel/Downloads/newpycam/pycam/pycam/Plugins/ParallelProcessing.py", line 232, in initialize_multiprocessing
    server_credentials=auth_key, local_port=local_port)
  File "/home/sel/Downloads/newpycam/pycam/pycam/Utils/threading.py", line 309, in init_threading
    __manager = TaskManager(address=address, authkey=server_credentials)
  File "/usr/lib/python3.5/multiprocessing/managers.py", line 435, in __init__
    self._authkey = process.AuthenticationString(authkey)
TypeError: string argument without an encoding

**Comment by sumpfralle** [comment]
thank you!
