### ISSUE TITLE
Error when trying to open STL

### ISSUE THREAD

**Issue by Deckweiss** [SebKuzminsky/pycam#146]
An unexpected exception occoured: please send the text below to the developers of PyCAM. Thanks a lot!
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pycam-0.6.4-py2.7.egg/pycam/Gui/Project.py", line 386, in gui_activity_guard_wrapper
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pycam-0.6.4-py2.7.egg/pycam/Gui/Project.py", line 524, in load_model_file
    detected_filetype = pycam.Importers.detect_file_type(filename)
  File "/usr/local/lib/python2.7/dist-packages/pycam-0.6.4-py2.7.egg/pycam/Importers/__init__.py", line 38, in detect_file_type
    from pycam.Importers.SVGDirectImporter import import_model as import_model_from_svg
  File "/usr/local/lib/python2.7/dist-packages/pycam-0.6.4-py2.7.egg/pycam/Importers/SVGDirectImporter.py", line 36, in <module>
    import svg.path
ImportError: No module named svg.path

Ubuntu 19.04
installed all dependencies, then ran setup.py and started the tool from cmd "pycam"

**Comment by sumpfralle** [comment]
Indeed you need to install the additional package `python-svg.path`. This piece of information was missing in the documentation for v0.6.x. I mentioned it now (28964fa54bb9cca441725bc2e62cae806c90ceee).

Thank you!
