### ISSUE TITLE
Error at launch

### ISSUE THREAD

**Issue by Charcor** [SebKuzminsky/pycam#149]
Traceback (most recent call last):
  File "/pycam-0.6.4/pycam/Gui/Project.py", line 386, in gui_activity_guard_wrapper
    result = func(self, *args, **kwargs)
  File "/pycam-0.6.4/pycam/Gui/Project.py", line 524, in load_model_file
    detected_filetype = pycam.Importers.detect_file_type(filename)
  File "/pycam-0.6.4/pycam/Importers/__init__.py", line 38, in detect_file_type
    from pycam.Importers.SVGDirectImporter import import_model as import_model_from_svg
  File "/pycam-0.6.4/pycam/Importers/SVGDirectImporter.py", line 36, in <module>
    import svg.path
ImportError: No module named svg.path

**Comment by sumpfralle** [comment]
You need to install the python module `svg.path`.

I improved the logging of this error now (7402a9ea24a6e5b3189c9bb097aa310037efd353 and cc9a12d3c2cbca3ce6ff41f8867ba0db9f401b16).
