### ISSUE TITLE
Exceptions on launch

### ISSUE THREAD

**Issue by jayMcBee** [SebKuzminsky/pycam#153]
Error shown when launching pycam:

An unexpected exception occoured: please send the text below to the developers of PyCAM. Thanks a lot!
Traceback (most recent call last):
  File "/home/user/Things/pycam-0.6.4/pycam/Gui/Project.py", line 386, in gui_activity_guard_wrapper
    result = func(self, *args, **kwargs)
  File "/home/user/Things/pycam-0.6.4/pycam/Gui/Project.py", line 524, in load_model_file
    detected_filetype = pycam.Importers.detect_file_type(filename)
  File "/home/user/Things/pycam-0.6.4/pycam/Importers/__init__.py", line 38, in detect_file_type
    from pycam.Importers.SVGDirectImporter import import_model as import_model_from_svg
  File "/home/user/Things/pycam-0.6.4/pycam/Importers/SVGDirectImporter.py", line 36, in <module>
    import svg.path
ImportError: No module named svg.path

**Comment by august9999** [comment]
i have installed python-svg.path and it solved

**Comment by jayMcBee** [comment]
Thanks, that helped.
Gotta brush up my Unix/Linux skills after a break!

BTW, the dependencies appear to be incomplete - I had to install a couple of additional packages in order to launch pycam w/o exceptions

**Comment by ArmoredBlood** [comment]
As another data point, I ran into the same issues on initial startup.

To resolve, I needed to run:
`sudo apt-get install python-gtkgext1 python-svg.path`.

![screenshot_3](https://user-images.githubusercontent.com/15917618/71326613-d3916d00-24c2-11ea-9abb-841dc2c2e87a.png)
