### ISSUE TITLE
Import error: no module named svg.path

### ISSUE THREAD

**Issue by august9999** [SebKuzminsky/pycam#154]
Hello, 
Could somebody know how to solve the following error:

> 

Enabled 2 parallel local processes
Skipping plugin /media/sf_Shared_Folder/pycam-0.6.4/pycam/Plugins/PathParameters.py: No module named enum
*** skipped 2 similar message(s) ***
Font directory: /media/sf_Shared_Folder/pycam-0.6.4/share/fonts
An unexpected exception occoured: please send the text below to the developers of PyCAM. Thanks a lot!
Traceback (most recent call last):
  File "/media/sf_Shared_Folder/pycam-0.6.4/pycam/Gui/Project.py", line 386, in gui_activity_guard_wrapper
    result = func(self, *args, **kwargs)
  File "/media/sf_Shared_Folder/pycam-0.6.4/pycam/Gui/Project.py", line 524, in load_model_file
    detected_filetype = pycam.Importers.detect_file_type(filename)
  File "/media/sf_Shared_Folder/pycam-0.6.4/pycam/Importers/__init__.py", line 38, in detect_file_type
    from pycam.Importers.SVGDirectImporter import import_model as import_model_from_svg
  File "/media/sf_Shared_Folder/pycam-0.6.4/pycam/Importers/SVGDirectImporter.py", line 36, in <module>
    import svg.path
ImportError: No module named svg.path

> 

I have tried version 0.6.4  on ubuntu 0.17 virtual machine
many thanks in advance

**Comment by august9999** [comment]
...ugraded ubuntu 17.10 to 18.04
then
sudo apt-get update -y
sudo apt-get install -y python-svg.path
and it works
