### ISSUE TITLE
Process pool viewer error

### ISSUE THREAD

**Issue by valeriob01** [SebKuzminsky/pycam#36]
reproducible: Clicking and scrolling in the process pool window. 

Event emitted: visualize-items
Traceback (most recent call last):
  File "/home/sel/Downloads/pycam/pycam/Plugins/ParallelProcessing.py", line 140, in update_process_pool_statistics
    stats = pycam.Utils.threading.get_pool_statistics()
  File "/home/sel/Downloads/pycam/pycam/Utils/threading.py", line 144, in get_pool_statistics
    return __manager.statistics().get_worker_statistics()
  File "<string>", line 2, in get_worker_statistics
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 773, in _callmethod
    raise convert_to_error(kind, result)
RuntimeError: dictionary changed size during iteration
Event emitted: visualize-items

**Comment by sumpfralle** [comment]
I think, it is fixed. Thank you!
