### ISSUE TITLE
Extrusion generates an unrecoverable error

### ISSUE THREAD

**Issue by jeromio** [SebKuzminsky/pycam#38]
Using pycam 0.6 and starting with an EPS file.

Used the default settings for Extrusion. "Extrude Model" cranked away for a few moments (5-10sec) and then locked up. Here is the traceback:
```
Traceback (most recent call last):
  File "/home/jeromio/pycam-0.6/pycam/Plugins/ModelExtrusion.py", line 119, in _extrude_model
    callback=progress.update)
  File "/home/jeromio/pycam-0.6/pycam/Geometry/Model.py", line 783, in extrude
    new_model = group.extrude(func=func, stepping=stepping)
  File "/home/jeromio/pycam-0.6/pycam/Geometry/Model.py", line 843, in extrude
    triangle_optimizer.optimize()
  File "/home/jeromio/pycam-0.6/pycam/Geometry/Model.py", line 1030, in optimize
    combined = Rectangle.combine_triangles(current, t)
  File "/home/jeromio/pycam-0.6/pycam/Geometry/Model.py", line 1135, in combine_triangles
    if abs(pdist(unique_verticies[0], unique_verticies[1]) - pdist(shared_vertices[0], shared_vertices[1])) < epsilon:
NameError: global name 'unique_verticies' is not defined
```

**Comment by sumpfralle** [comment]
This was fixed in is fixed in the current development .
