### ISSUE TITLE
Uhexpected exception

### ISSUE THREAD

**Issue by akwusmc** [SebKuzminsky/pycam#66]
This happened as I tried to open a .dxf.

Pycam 0.6.1 , Ubuntu 16.04.3 LTS 32-bit

An unexpected exception occoured: please send the text below to the developers of PyCAM. Thanks a lot!
Traceback (most recent call last):
  File "/home/anthony/Desktop/pycam-0.6.1/pycam/Gui/Project.py", line 633, in gui_activity_guard_wrapper
    result = func(self, *args, **kwargs)
  File "/home/anthony/Desktop/pycam-0.6.1/pycam/Gui/Project.py", line 861, in load_model_file
    callback=progress.update)
  File "/home/anthony/Desktop/pycam-0.6.1/pycam/Importers/DXFImporter.py", line 881, in import_model
    callback=callback)
  File "/home/anthony/Desktop/pycam-0.6.1/pycam/Importers/DXFImporter.py", line 117, in __init__
    self.parse_content()
  File "/home/anthony/Desktop/pycam-0.6.1/pycam/Importers/DXFImporter.py", line 250, in parse_content
    self.parse_arc(circle=True)
  File "/home/anthony/Desktop/pycam-0.6.1/pycam/Importers/DXFImporter.py", line 844, in parse_arc
    xy_point_coords = pycam.Geometry.get_points_of_arc(center, radius, angle_start,
AttributeError: 'module' object has no attribute 'get_points_of_arc'

**Comment by sumpfralle** [comment]
This one is fixed in the repository: 3655a263a0f4fcaa7b6cfc051158cfc2916f70d4

Maybe you want to apply this trivial change manually or switch to the head of the repository.
