### ISSUE TITLE
string argument without an encoding

### ISSUE THREAD

**Issue by valeriob01** [SebKuzminsky/pycam#96]
:~/Downloads/newpycam/pycam/pycam$ ./run_gui.py --start-server-only --server-auth-key XXXXX
Enabled 4 parallel local processes
Allow remote processing
Traceback (most recent call last):
  File "./run_gui.py", line 291, in <module>
    main_func()
  File "./run_gui.py", line 279, in main_func
    exit_code = execute(parser, args, pycam)
  File "./run_gui.py", line 192, in execute
    server_credentials=args.server_authkey)
  File "/home/sel/Downloads/newpycam/pycam/pycam/Utils/threading.py", line 309, in init_threading
    __manager = TaskManager(address=address, authkey=server_credentials)
  File "/usr/lib/python3.4/multiprocessing/managers.py", line 447, in __init__
    self._authkey = process.AuthenticationString(authkey)
TypeError: string argument without an encoding

**Comment by sumpfralle** [comment]
thank you!
